import { Archive, ArrowLeft, History, Plus, Save, Trash2 } from 'lucide-react';
import { useState } from 'react';
import type { Course, CustomField, MediaLink } from '../types.js';
import { MarkdownField } from './MarkdownField.js';
type Tab = 'general' | 'content' | 'custom' | 'history';

export function CourseEditor({ course, isNew, onChange, onSave, onClose, onArchive, onHistory, busy }: { course: Course; isNew: boolean; onChange: (course: Course) => void; onSave: () => void; onClose: () => void; onArchive?: () => void; onHistory?: () => void; busy: boolean }) {
  const [tab, setTab] = useState<Tab>('general');
  const set = <K extends keyof Course>(key: K, value: Course[K]) => onChange({ ...course, [key]: value });
  const updateField = (index: number, patch: Partial<CustomField>) => set('customFields', course.customFields.map((field, position) => position === index ? { ...field, ...patch } : field));
  const updateMedia = (index: number, patch: Partial<MediaLink>) => set('mediaLinks', course.mediaLinks.map((media, position) => position === index ? { ...media, ...patch } : media));
  const tabs: Array<{ id: Tab; label: string }> = [{ id: 'general', label: 'General' }, { id: 'content', label: 'Content' }, { id: 'custom', label: 'Custom fields' }, { id: 'history', label: 'History' }];
  return <div className="editor-page-wrap"><section className="editor-page" aria-label="Course editor">
    <header className="editor-page-header"><button className="back-button" onClick={onClose}><ArrowLeft size={17} /> Course library</button><div className="editor-title-row"><div><p className="eyebrow">{isNew ? 'New course' : `Course #${course.id}`}</p><h1 dir="auto">{course.name || 'Untitled course'}</h1></div><div className="head-actions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" onClick={onSave} disabled={busy}><Save size={16} />{busy ? 'Saving…' : 'Save course'}</button></div></div><div className="editor-tabs" role="tablist" aria-label="Course sections">{tabs.map(item => <button key={item.id} role="tab" aria-selected={tab === item.id} onClick={() => setTab(item.id)}>{item.label}{item.id === 'custom' && <span>{course.customFields.length}</span>}</button>)}</div></header>
    <div className="editor-document" role="tabpanel">
      {tab === 'general' && <><div className="section-intro"><h2>Course details</h2><p>The stable identity and customer-facing summary for this course.</p></div><div className="two-col"><label className="field"><span>Course ID</span><input value={course.id} disabled={!isNew} onChange={event => set('id', event.target.value)} placeholder="e.g. 83" /><small>This ID cannot change after creation.</small></label><label className="field"><span>Status</span><select value={course.status} onChange={event => set('status', event.target.value as Course['status'])}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select></label></div><label className="field"><span>Course name</span><input dir="auto" value={course.name} onChange={event => set('name', event.target.value)} /></label><MarkdownField label="Short description" value={course.shortDescription} rows={4} onChange={value => set('shortDescription', value)} /><MarkdownField label="Price" value={course.price} rows={4} hint="Freeform pricing in any language." onChange={value => set('price', value)} /><div className="section-head"><div><h3>External media</h3><p>Link brochures, videos, documents, or images.</p></div><button className="secondary" onClick={() => set('mediaLinks', [...course.mediaLinks, { label: '', url: '', type: 'OTHER', description: '' }])}><Plus size={16} /> Add link</button></div>{course.mediaLinks.length === 0 && <div className="inline-empty">No media links have been added.</div>}{course.mediaLinks.map((media, index) => <article className="nested-card" key={index}><div className="two-col"><label className="field"><span>Label</span><input value={media.label} onChange={event => updateMedia(index, { label: event.target.value })} /></label><label className="field"><span>Type</span><select value={media.type} onChange={event => updateMedia(index, { type: event.target.value as MediaLink['type'] })}>{['OTHER', 'PDF', 'VIDEO', 'IMAGE', 'DOCUMENT'].map(type => <option key={type}>{type}</option>)}</select></label></div><label className="field"><span>URL</span><input type="url" value={media.url} onChange={event => updateMedia(index, { url: event.target.value })} /></label><label className="field"><span>Description</span><input dir="auto" value={media.description} onChange={event => updateMedia(index, { description: event.target.value })} /></label><button className="danger-text" onClick={() => set('mediaLinks', course.mediaLinks.filter((_, position) => position !== index))}><Trash2 size={15} /> Remove link</button></article>)}</>}
      {tab === 'content' && <><div className="section-intro"><h2>Sales content</h2><p>Write the source material the agent will use to explain and sell this course.</p></div><MarkdownField label="Curriculum" value={course.curriculum} rows={13} onChange={value => set('curriculum', value)} /><MarkdownField label="How to sell" value={course.howToSell} rows={11} hint="Internal. Available only to privileged sales-agent API keys." onChange={value => set('howToSell', value)} /></>}
      {tab === 'custom' && <><div className="section-head first"><div><h2>Custom fields</h2><p>Flexible Markdown knowledge for the sales agent.</p></div><button className="secondary" onClick={() => set('customFields', [...course.customFields, { name: '', content: '', visibility: 'INTERNAL' }])}><Plus size={16} /> Add field</button></div>{course.customFields.length === 0 && <div className="inline-empty">No custom fields yet. Add one when this course needs extra context.</div>}{course.customFields.map((field, index) => <article className="nested-card" key={index}><div className="two-col"><label className="field"><span>Field name</span><input dir="auto" value={field.name} onChange={event => updateField(index, { name: event.target.value })} /></label><label className="field"><span>Visibility</span><select value={field.visibility} onChange={event => updateField(index, { visibility: event.target.value as CustomField['visibility'] })}><option value="INTERNAL">Internal</option><option value="PUBLIC">Public</option></select></label></div><MarkdownField label="Content" value={field.content} onChange={value => updateField(index, { content: value })} /><button className="danger-text" onClick={() => set('customFields', course.customFields.filter((_, position) => position !== index))}><Trash2 size={15} /> Remove field</button></article>)}</>}
      {tab === 'history' && <div className="history-intro"><History size={28} /><h2>Course history</h2><p>Review saved revisions and restore an earlier version when necessary.</p>{onHistory ? <button className="primary" onClick={onHistory}><History size={16} /> View revision history</button> : <p className="muted">History becomes available after the course is created.</p>}</div>}
    </div>
    {!isNew && onArchive && <footer className="editor-danger-zone"><div><strong>Archive course</strong><p>Remove this course from the active library without deleting its history.</p></div><button className="danger-text bordered" onClick={onArchive}><Archive size={16} /> Archive</button></footer>}
  </section></div>;
}
