import { FileUp, Sparkles } from 'lucide-react';
import { useState } from 'react';
import { api } from '../api.js';
import type { Course } from '../types.js';

type Question = { field: keyof Pick<Course, 'id' | 'name' | 'shortDescription' | 'price' | 'curriculum' | 'howToSell'>; question: string };
type ImportResult = { draft: Course; questions: Question[] };

export function PdfImport({ onImport, focused = false }: { onImport: (course: Course) => void; focused?: boolean }) {
  const [file, setFile] = useState<File | null>(null); const [result, setResult] = useState<ImportResult | null>(null); const [answers, setAnswers] = useState<Partial<Record<Question['field'], string>>>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function extract() { if (!file) return setError('Choose a PDF file to import.'); setBusy(true); setError(''); try { const body = new FormData(); body.append('pdf', file); const imported = await api<ImportResult>('/admin/courses/import-pdf', { method: 'POST', body }); if (imported.questions.length === 0) onImport(imported.draft); else setResult(imported); } catch (caught) { setError(caught instanceof Error ? caught.message : 'The PDF could not be imported.'); } finally { setBusy(false); } }
  const input = <input id="course-pdf" className={focused ? 'visually-hidden' : ''} aria-label="Course PDF" type="file" accept="application/pdf,.pdf" onChange={event => setFile(event.target.files?.[0] || null)} />;
  if (result) return <section className="pdf-import-result" aria-label="PDF import questions"><div><p className="eyebrow">A few details are missing</p><h2>Complete the course import</h2><p>Answer these questions, or continue to the editor and fill them in yourself.</p></div>{result.questions.map(({ field, question }) => <label className="field" key={field}><span>{question}</span><input value={answers[field] || ''} onChange={event => setAnswers({ ...answers, [field]: event.target.value })} /></label>)}<div className="head-actions"><button className="secondary" onClick={() => onImport(result.draft)}>Fill remaining data manually</button><button className="primary" onClick={() => onImport({ ...result.draft, ...answers })}>Apply answers</button></div></section>;
  if (focused) return <section className="pdf-import pdf-import-focused" aria-label="Import course from PDF">{input}<img className="pdf-import-illustration" src="/assets/pdf-import-illustration.png" alt="Professional organizing PDF course data into structured learning information" /><button className="secondary" disabled={busy} onClick={extract}><Sparkles size={16} />{busy ? 'Extracting…' : 'Extract course details'}</button>{file && <small className="pdf-selected-file">Selected: {file.name}</small>}{error && <p className="error" role="alert">{error}</p>}</section>;
  return <section className="pdf-import" aria-label="Import course from PDF"><img className="pdf-import-illustration" src="/assets/pdf-import-illustration.png" alt="Professional organizing PDF course data into structured learning information" /><div className="pdf-import-content"><p className="eyebrow">Course import</p><h2>Start with a PDF</h2><p>Use AI to extract course details, then review everything before saving.</p></div><label className="file-picker"><FileUp size={18} /><span>Course PDF</span>{input}{file && <small>{file.name}</small>}</label><button className="secondary" disabled={busy} onClick={extract}><Sparkles size={16} />{busy ? 'Extracting…' : 'Extract course details'}</button>{error && <p className="error" role="alert">{error}</p>}</section>;
}
